CONST_TARGETS = ['macrodetails-height/Height',
                 'macrodetails-proportions/BodyProportions',
                 'macrodetails-universal/Muscle',
                 'macrodetails-universal/Weight']
BETA_TARGETS = ['macrodetails/Gender']
AGE_TARGET = ['macrodetails/Age']
ETHNICITY = ['macrodetails/African',
             'macrodetails/Asian',
             'macrodetails/Caucasian']
EXPRESSIONS = ['anger01', 'attention01', 'boring01', 'cry01', 'determination01', 'determination02', 'disgust01', 'doubt01',
               'effort01', 'effort02', 'effort03', 'fear01', 'fear02', 'fear03', 'fear04', 'laugh01', 'laugh02', 'sad01',
               'sad02', 'sceptical01', 'sleep01', 'smile01', 'smile02', 'smile03', 'smile04', 'smile05', 'stunned01', 'surprise01',
               'surprise02', 'threaten01', 'threaten02', 'vocalize01']
EYEBROWS = ['eyebrow002', 'eyebrow004', 'eyebrow006', 'eyebrow008', 'eyebrow010', 'eyebrow012', 'eyebrow001',
            'eyebrow003', 'eyebrow005', 'eyebrow007', 'eyebrow009', 'eyebrow011']
EYE_COLORS = ['deepblue', 'grey', 'lightblue', 'bluegreen', 'brownlight', 'blue', 'brown', 'green', 'ice']
INVISIBLE_SKINS = [
    'Caucasion_Male_Tattooed_Skin/Caucasion_TatooedMale_Skin_Difuse.mhmat',
    'Kamden_skin/Kamden_Skin.mhmat',
    'Light_Skin_Female_Bronze/light_skin_female_bronze.mhmat',
    'Light_Skin_Female_Bronze_with_Makeup/light_skin_female_bronze_makeup.mhmat',
    'Light_Skin_Female_Freckles/light_skin_female_freckles.mhmat',
    'Light_Skin_Female_Ginger/light_skin_female_ginger.mhmat',
    'Light_Skin_Female_Ginger_2/light_skin_female_ginger2.mhmat',
    'Light_Skin_Female_Ginger_with_Makeup/light_skin_female_ginger_makeup.mhmat',
    'Light_Skin_Female_with_Violet_Makeup/light_skin_female_violet_makeup.mhmat',
    'Light_Skin_Male_Bronze/light_skin_male_bronze.mhmat',
    'Light_Skin_Male_Freckles/light_skin_male_freckles.mhmat',
    'Light_Skin_Male_Ginger/light_skin_male_ginger.mhmat',
    'Light_Skin_Male_with_Emo_Eyes/light_skin_male_emoeyes.mhmat',
    'Light_Skin_Male_with_Eyeliner/light_skin_male_eyeliner.mhmat',
    'Light_Skin_Male_with_Goth_Makeup/light_skin_male_goth.mhmat',
    'Light_Skin_with_Makeup/light_skin_makeup.mhmat',
    'Light_Skin_with_Natural_Makeup/lightskinfemale_natural_makeup.mhmat',
]
SKINS = [
    'middleage_african_female/middleage_african_female.mhmat',
    'middleage_african_male/middleage_african_male.mhmat',
    'middleage_asian_female/middleage_asian_female.mhmat',
    'middleage_asian_male/middleage_asian_male.mhmat',
    'middleage_caucasian_female/middleage_caucasian_female.mhmat',
    'middleage_caucasian_male/middleage_caucasian_male.mhmat',
    'old_african_female/old_african_female.mhmat',
    'old_african_male/old_african_male.mhmat',
    'old_asian_female/old_asian_female.mhmat',
    'old_asian_male/old_asian_male.mhmat',
    'old_caucasian_female/old_caucasian_female.mhmat',
    'old_caucasian_male/old_caucasian_male.mhmat',
    'young_african_female/young_african_female.mhmat',
    'young_african_male/young_african_male.mhmat',
    'young_asian_female/young_asian_female.mhmat',
    'young_asian_male/young_asian_male.mhmat',
    'young_caucasian_female/young_caucasian_female.mhmat',
    'young_caucasian_female/young_caucasian_female2.mhmat',
    'young_caucasian_male/young_caucasian_male.mhmat',
    'young_caucasian_male/young_caucasian_male2.mhmat',
]
COMMUNITY_SKINS = [
    'Caucasion_Male_Tattooed_Skin/Caucasion_TatooedMale_Skin_Difuse.mhmat',
    'creamy_female/creamy_female.mhmat',
    'Darthfurby_Caucasian_Female/darthfurby_caucasian_female.mhmat',
    'elfskinsohlen/elfskinsohlen.mhmat',
    'Elven_skin/elfskin.mhmat',
    'Elvs_Chocolate_Ebony_YMG_skin/Choc_ebony.mhmat',
    'Elvs_Ebony_YMG_skin/ebonymalegen.mhmat',
    'Elvs_Lady_Henna_skin1/lady_henna_skin1.mhmat',
    'Elvs_Makeup_Recolor1_for_YBF_skin/y_bk_f_recolor_make1.mhmat',
    'Jammers_skin/black_jammers.mhmat',
    'Kamden_skin/Kamden_Skin.mhmat',
    'Light_Skin_Female_Bronze/light_skin_female_bronze.mhmat',
    'Light_Skin_Female_Bronze_with_Makeup/light_skin_female_bronze_makeup.mhmat',
    'Light_Skin_Female_Freckles/light_skin_female_freckles.mhmat',
    'Light_Skin_Female_Ginger/light_skin_female_ginger.mhmat',
    'Light_Skin_Female_Ginger_2/light_skin_female_ginger2.mhmat',
    'Light_Skin_Female_Ginger_with_Makeup/light_skin_female_ginger_makeup.mhmat',
    'Light_Skin_Female_with_Violet_Makeup/light_skin_female_violet_makeup.mhmat',
    'Light_Skin_Male_Bronze/light_skin_male_bronze.mhmat',
    'Light_Skin_Male_Freckles/light_skin_male_freckles.mhmat',
    'Light_Skin_Male_Ginger/light_skin_male_ginger.mhmat',
    'Light_Skin_Male_with_Emo_Eyes/light_skin_male_emoeyes.mhmat',
    'Light_Skin_Male_with_Eyeliner/light_skin_male_eyeliner.mhmat',
    'Light_Skin_Male_with_Goth_Makeup/light_skin_male_goth.mhmat',
    'Light_Skin_with_Makeup/light_skin_makeup.mhmat',
    'Light_Skin_with_Natural_Makeup/lightskinfemale_natural_makeup.mhmat',
    'Middle_Aged_Eurasian_Female/middleage_eurasian_female.mhmat',
    'mohawk/mohawk.mhmat',
    'Old_Eurasian_Female/old_eurasian_female.mhmat',
    'Old_Eurasian_Male/old_eurasian_male.mhmat',
    'skin_male_african_middleage/skin_male_african_middleage.mhmat',
    'Uniform_skin_texture/skin_texture.mhmat',
    'Young_Eurasian_Female/young_eurasian_female.mhmat',
    'Young_Lightskinned_Male_G_Recolor/Elvs_lightskinned_male1.mhmat',
]
SPECIAL_SKINS = [
    'toon01/toon01.mhmat',
    'young_caucasian_female/young_caucasian_female_special_suit.mhmat',
    'young_caucasian_male/young_caucasian_male_special_suit.mhmat',
]
COMMUNITY_SPECIAL_SKINS = [
    'Annotated_skin/AnnotatedSkin.mhmat',
    'blue_Leopard_Skin/BlueLeopardSkin.mhmat',
    'White_Walker_Skin/MyCoolSkin.mhmat',
    'Modified_Caucasian_Female_skin_Darker_More_visible_nipple/Nipple_Skin.mhmat',
    'Orkifyheadtarget_custom_skin/Orkskin.mhmat',
    'zombie_Skin/Zombie.mhmat',
    'Forsaken_Blue_Bones/a_forsaken_blue_bones.mhmat',
    'baboon_people/baboon.mhmat',
    'Aksel_Skin/character_Aksel_Skin.mhmat',
    'Darthfurby_Caucasian_Female/darthfurby_caucasian_female_toon.mhmat',
    'Mermaid_One/mermaid01.mhmat',
]

EYELASHES = ['eyelashes01', 'eyelashes02', 'eyelashes03', 'eyelashes04']
EYES = ['high-poly']
TONGUES = ['tongue01']
TEETH = ['teeth_base', 'teeth_shape01', 'teeth_shape02', 'teeth_shape03', 'teeth_shape04', 'teeth_shape05']

RESTRICTED_TARGETS = {
    # 'TARGET_NAME': [DEFAULT_VAL, MIN_VAL, MAX_VAL]
    'eyebrows/eyebrows-angle-down|up'         : [0.0, -0.8, 0.8],
    'eyebrows/eyebrows-trans-backward|forward': [0.0, -0.4, 0.3],
    'eyebrows/eyebrows-trans-down|up'         : [0.0, -0.5, 1.0],
    'forehead/forehead-nubian-decr|incr'      : [0.0, -0.3, 0.3],
    'forehead/forehead-scale-vert-decr|incr'  : [0.0, -0.3, 0.3],
    'forehead/forehead-temple-decr|incr'      : [0.0, -0.5, 0.5],
    'forehead/forehead-trans-backward|forward': [0.0, -0.2, 0.6],
    'head/head-age-decr|incr'                 : [0.0, -1.0, 1.0],
    'head/head-angle-in|out'                  : [0.0, -0.2, 0.2],
    'head/head-back-scale-depth-decr|incr'    : [0.0, -0.2, 0.2],
    'head/head-fat-decr|incr'                 : [0.0, -1.0, 1.0],
    'head/head-scale-depth-decr|incr'         : [0.0, -0.6, 0.6],
    'head/head-scale-horiz-decr|incr'         : [0.0, -0.3, 0.3],
    'head/head-scale-vert-decr|incr'          : [0.0, -0.3, 0.3],
    'head/head-trans-backward|forward'        : [0.0, -0.1, 0.1],
    'head/head-trans-down|up'                 : [0.0, -0.6, 0.3],
    'head/head-trans-in|out'                  : [0.0, -0.6, 0.4],
}
SYMMETRICAL_TARGETS = [
    'cheek/X-cheek-bones-decr|incr',
    'cheek/X-cheek-inner-decr|incr',
    'cheek/X-cheek-trans-down|up',
    'cheek/X-cheek-volume-decr|incr',
    'ears/X-ear-flap-decr|incr',
    'ears/X-ear-lobe-decr|incr',
    'ears/X-ear-rot-backward|forward',
    'ears/X-ear-scale-decr|incr',
    'ears/X-ear-scale-depth-decr|incr',
    'ears/X-ear-scale-vert-decr|incr',
    'ears/X-ear-shape-pointed|triangle',
    'ears/X-ear-shape-square|round',
    'ears/X-ear-trans-backward|forward',
    'ears/X-ear-trans-down|up',
    'ears/X-ear-wing-decr|incr',
    'eyes/X-eye-bag-decr|incr',
    'eyes/X-eye-bag-height-decr|incr',
    'eyes/X-eye-bag-in|out',
    'eyes/X-eye-corner1-down|up',
    'eyes/X-eye-corner2-down|up',
    'eyes/X-eye-epicanthus-in|out',
    'eyes/X-eye-eyefold-angle-down|up',
    'eyes/X-eye-eyefold-concave|convex',
    'eyes/X-eye-eyefold-down|up',
    'eyes/X-eye-height1-decr|incr',
    'eyes/X-eye-height2-decr|incr',
    'eyes/X-eye-height3-decr|incr',
    'eyes/X-eye-push1-in|out',
    'eyes/X-eye-push2-in|out',
    'eyes/X-eye-scale-decr|incr',
    'eyes/X-eye-trans-down|up',
    'eyes/X-eye-trans-in|out',
]
HEAD_SHAPE = [
    'head/head-diamond',
    'head/head-invertedtriangular',
    'head/head-oval',
    'head/head-rectangular',
    'head/head-round',
    'head/head-square',
    'head/head-triangular',
]
UNRESTRICTED_TARGETS = [
    'chin/chin-bones-decr|incr',
    'chin/chin-cleft-decr|incr',
    'chin/chin-height-decr|incr',
    'chin/chin-jaw-drop-decr|incr',
    'chin/chin-prognathism-decr|incr',
    'chin/chin-prominent-decr|incr',
    'chin/chin-width-decr|incr',
    'mouth/mouth-angles-down|up',
    'mouth/mouth-cupidsbow-decr|incr',
    'mouth/mouth-cupidsbow-width-decr|incr',
    'mouth/mouth-dimples-in|out',
    'mouth/mouth-laugh-lines-in|out',
    'mouth/mouth-lowerlip-ext-down|up',
    'mouth/mouth-lowerlip-height-decr|incr',
    'mouth/mouth-lowerlip-middle-down|up',
    'mouth/mouth-lowerlip-volume-decr|incr',
    'mouth/mouth-lowerlip-width-decr|incr',
    'mouth/mouth-philtrum-volume-decr|incr',
    'mouth/mouth-scale-depth-decr|incr',
    'mouth/mouth-scale-horiz-decr|incr',
    'mouth/mouth-scale-vert-decr|incr',
    'mouth/mouth-trans-backward|forward',
    'mouth/mouth-trans-down|up',
    'mouth/mouth-trans-in|out',
    'mouth/mouth-upperlip-ext-down|up',
    'mouth/mouth-upperlip-height-decr|incr',
    'mouth/mouth-upperlip-middle-down|up',
    'mouth/mouth-upperlip-volume-decr|incr',
    'mouth/mouth-upperlip-width-decr|incr',
    'nose/nose-base-down|up',
    'nose/nose-compression-compress|uncompress',
    'nose/nose-flaring-decr|incr',
    'nose/nose-nostrils-angle-down|up',
    'nose/nose-nostrils-width-decr|incr',
    'nose/nose-point-down|up',
    'nose/nose-point-width-decr|incr',
    'nose/nose-scale-horiz-decr|incr',
    'nose/nose-scale-vert-decr|incr',
    'nose/nose-septumangle-decr|incr',
    'nose/nose-trans-backward|forward',
    'nose/nose-trans-down|up',
    'nose/nose-trans-in|out',
    'nose/nose-volume-decr|incr',
    'nose/nose-width1-decr|incr',
    'nose/nose-width2-decr|incr',
    'nose/nose-width3-decr|incr',
    'nose/nose-hump-decr|incr',
    'nose/nose-scale-depth-decr|incr',
    'nose/nose-greek-decr|incr',
    'nose/nose-curve-concave|convex',
]
FACE_TARGETS = [
    'cheek/l-cheek-bones-decr|incr',
    'cheek/l-cheek-inner-decr|incr',
    'cheek/l-cheek-trans-down|up',
    'cheek/l-cheek-volume-decr|incr',
    'cheek/r-cheek-bones-decr|incr',
    'cheek/r-cheek-inner-decr|incr',
    'cheek/r-cheek-trans-down|up',
    'cheek/r-cheek-volume-decr|incr',

    'chin/chin-bones-decr|incr',
    'chin/chin-cleft-decr|incr',
    'chin/chin-height-decr|incr',
    'chin/chin-jaw-drop-decr|incr',
    'chin/chin-prognathism-decr|incr',
    'chin/chin-prominent-decr|incr',
    'chin/chin-width-decr|incr',

    'ears/l-ear-flap-decr|incr',
    'ears/l-ear-lobe-decr|incr',
    'ears/l-ear-rot-backward|forward',
    'ears/l-ear-scale-decr|incr',
    'ears/l-ear-scale-depth-decr|incr',
    'ears/l-ear-scale-vert-decr|incr',
    'ears/l-ear-shape-pointed|triangle',
    'ears/l-ear-shape-square|round',
    'ears/l-ear-trans-backward|forward',
    'ears/l-ear-trans-down|up',
    'ears/l-ear-wing-decr|incr',
    'ears/r-ear-flap-decr|incr',
    'ears/r-ear-lobe-decr|incr',
    'ears/r-ear-rot-backward|forward',
    'ears/r-ear-scale-decr|incr',
    'ears/r-ear-scale-depth-decr|incr',
    'ears/r-ear-scale-vert-decr|incr',
    'ears/r-ear-shape-pointed|triangle',
    'ears/r-ear-shape-square|round',
    'ears/r-ear-trans-backward|forward',
    'ears/r-ear-trans-down|up',
    'ears/r-ear-wing-decr|incr',

    'eyebrows/eyebrows-angle-down|up',
    'eyebrows/eyebrows-trans-backward|forward',
    'eyebrows/eyebrows-trans-down|up',

    'eyes/l-eye-bag-decr|incr',
    'eyes/l-eye-bag-height-decr|incr',
    'eyes/l-eye-bag-in|out',
    'eyes/l-eye-corner1-down|up',
    'eyes/l-eye-corner2-down|up',
    'eyes/l-eye-epicanthus-in|out',
    'eyes/l-eye-eyefold-angle-down|up',
    'eyes/l-eye-eyefold-concave|convex',
    'eyes/l-eye-eyefold-down|up',
    'eyes/l-eye-height1-decr|incr',
    'eyes/l-eye-height2-decr|incr',
    'eyes/l-eye-height3-decr|incr',
    'eyes/l-eye-push1-in|out',
    'eyes/l-eye-push2-in|out',
    'eyes/l-eye-scale-decr|incr',
    'eyes/l-eye-trans-down|up',
    'eyes/l-eye-trans-in|out',
    'eyes/r-eye-bag-decr|incr',
    'eyes/r-eye-bag-height-decr|incr',
    'eyes/r-eye-bag-in|out',
    'eyes/r-eye-corner1-down|up',
    'eyes/r-eye-corner2-down|up',
    'eyes/r-eye-epicanthus-in|out',
    'eyes/r-eye-eyefold-angle-down|up',
    'eyes/r-eye-eyefold-concave|convex',
    'eyes/r-eye-eyefold-down|up',
    'eyes/r-eye-height1-decr|incr',
    'eyes/r-eye-height2-decr|incr',
    'eyes/r-eye-height3-decr|incr',
    'eyes/r-eye-push1-in|out',
    'eyes/r-eye-push2-in|out',
    'eyes/r-eye-scale-decr|incr',
    'eyes/r-eye-trans-down|up',
    'eyes/r-eye-trans-in|out',

    'forehead/forehead-nubian-decr|incr',
    'forehead/forehead-scale-vert-decr|incr',
    'forehead/forehead-temple-decr|incr',
    'forehead/forehead-trans-backward|forward',
    'head/head-age-decr|incr',
    'head/head-angle-in|out',
    'head/head-back-scale-depth-decr|incr',
    'head/head-diamond',
    'head/head-fat-decr|incr',
    'head/head-invertedtriangular',
    'head/head-oval',
    'head/head-rectangular',
    'head/head-round',
    'head/head-scale-depth-decr|incr',
    'head/head-scale-horiz-decr|incr',
    'head/head-scale-vert-decr|incr',
    'head/head-square',
    'head/head-trans-backward|forward',
    'head/head-trans-down|up',
    'head/head-trans-in|out',
    'head/head-triangular',

    'mouth/mouth-angles-down|up',
    'mouth/mouth-cupidsbow-decr|incr',
    'mouth/mouth-cupidsbow-width-decr|incr',
    'mouth/mouth-dimples-in|out',
    'mouth/mouth-laugh-lines-in|out',
    'mouth/mouth-lowerlip-ext-down|up',
    'mouth/mouth-lowerlip-height-decr|incr',
    'mouth/mouth-lowerlip-middle-down|up',
    'mouth/mouth-lowerlip-volume-decr|incr',
    'mouth/mouth-lowerlip-width-decr|incr',
    'mouth/mouth-philtrum-volume-decr|incr',
    'mouth/mouth-scale-depth-decr|incr',
    'mouth/mouth-scale-horiz-decr|incr',
    'mouth/mouth-scale-vert-decr|incr',
    'mouth/mouth-trans-backward|forward',
    'mouth/mouth-trans-down|up',
    'mouth/mouth-trans-in|out',
    'mouth/mouth-upperlip-ext-down|up',
    'mouth/mouth-upperlip-height-decr|incr',
    'mouth/mouth-upperlip-middle-down|up',
    'mouth/mouth-upperlip-volume-decr|incr',
    'mouth/mouth-upperlip-width-decr|incr',
    'nose/nose-base-down|up',
    'nose/nose-compression-compress|uncompress',
    'nose/nose-flaring-decr|incr',
    'nose/nose-nostrils-angle-down|up',
    'nose/nose-nostrils-width-decr|incr',
    'nose/nose-point-down|up',
    'nose/nose-point-width-decr|incr',
    'nose/nose-scale-horiz-decr|incr',
    'nose/nose-scale-vert-decr|incr',
    'nose/nose-septumangle-decr|incr',
    'nose/nose-trans-backward|forward',
    'nose/nose-trans-down|up',
    'nose/nose-trans-in|out',
    'nose/nose-volume-decr|incr',
    'nose/nose-width1-decr|incr',
    'nose/nose-width2-decr|incr',
    'nose/nose-width3-decr|incr',
    'nose/nose-hump-decr|incr',
    'nose/nose-scale-depth-decr|incr',
    'nose/nose-greek-decr|incr',
    'nose/nose-curve-concave|convex',
]

CONSTANT_KEYS = CONST_TARGETS + BETA_TARGETS + AGE_TARGET + EXPRESSIONS + EYEBROWS + EYE_COLORS + SKINS + COMMUNITY_SKINS + SPECIAL_SKINS + COMMUNITY_SPECIAL_SKINS + \
                EYELASHES + EYES + TONGUES + TEETH + UNRESTRICTED_TARGETS + list(RESTRICTED_TARGETS.keys()) + SYMMETRICAL_TARGETS + HEAD_SHAPE


def is_constant_key(key):
    try:
        CONSTANT_KEYS.index(key)
        return True
    except ValueError:
        return False
